"""Unit tests for synthesis note parsing used by the dashboard."""
from pathlib import Path

from transcript_analyzer.obsidian.writer import SYNTH_BEGIN, SYNTH_END, write_managed
from transcript_analyzer.web import synth_reader
from conftest import make_record


def _wrap(body: str) -> str:
    return f"{SYNTH_BEGIN}\n{body.strip()}\n{SYNTH_END}\n"


def test_parse_digest_claims_and_headline(cfg):
    body = _wrap(
        """
**Pricing got locked; Angela owns the deck.**

## Decisions
- Angela will review the pricing deck by Friday. ([[2026-07-01 chat-with-angela]])
- We keep the freemium tier. ([[2026-07-01 chat-with-angela]])

## Open
- Still need legal sign-off. ([[2026-07-01 chat-with-angela]])

See [[Commitments]] for everything currently open.

---
_Generated by transcript-analyzer synthesis._
"""
    )
    by_stem = {
        "2026-07-01 chat-with-angela": make_record(
            tid="abc",
            title="2026-07-01 chat-with-angela",
            note_path="/vault/Transcript Insights/2026-07-01 chat-with-angela.md",
        )
    }
    headline, sections = synth_reader.parse_digest(body, by_stem)
    assert "Pricing got locked" in headline
    assert len(sections) == 2
    assert sections[0].title == "Decisions"
    assert sections[0].claims[0].transcript_id == "abc"
    assert "Angela will review" in sections[0].claims[0].text
    assert "[[" not in sections[0].claims[0].text


def test_latest_digest_prefers_today(cfg):
    digests = cfg.vault.insights_path / "Digests"
    digests.mkdir(parents=True)
    older = digests / "2026-07-10.md"
    older.write_text(
        "---\nsynth: true\n---\n# Digest\n\n"
        + _wrap("**Old headline.**\n\n## Notes\n- Something. ([[x]])\n"),
        encoding="utf-8",
    )
    today = digests / "2026-07-17.md"
    today.write_text(
        "---\nsynth: true\n---\n# Digest\n\n"
        + _wrap("**Today's headline.**\n\n## Notes\n- Fresh. ([[x]])\n"),
        encoding="utf-8",
    )
    from datetime import date

    view = synth_reader.latest_digest(cfg, {}, today=date(2026, 7, 17))
    assert view.exists
    assert view.date == "2026-07-17"
    assert "Today's headline" in view.headline


def test_commitments_from_records():
    recs = [
        make_record(tid="1", open_items=["Ship deck"], title="A", date_str="2026-07-02"),
        make_record(tid="2", open_items=[], title="B", date_str="2026-07-01"),
        make_record(tid="3", open_items=["Call bank", "Email LP"], title="C", date_str="2026-07-03"),
    ]
    groups = synth_reader.commitments_from_records(recs)
    assert len(groups) == 2
    assert groups[0].transcript_id == "1"
    assert groups[1].items == ["Call bank", "Email LP"]


def test_parse_person(cfg):
    body = """
Angela is the pricing lead at Acme.

**Email:** angela@acme.com

## What they care about
- Clear timeline on the deck. ([[2026-07-01 chat-with-angela]])

## Open threads
- Waiting on legal. ([[2026-07-01 chat-with-angela]])

## Conversations
- [[2026-07-01 chat-with-angela]] · 2026-07-01
"""
    by_stem = {
        "2026-07-01 chat-with-angela": make_record(tid="abc", title="chat")
    }
    card = synth_reader.parse_person(body, by_stem)
    assert "pricing lead" in card.who
    assert len(card.cares_about) == 1
    assert card.cares_about[0].transcript_id == "abc"
    assert len(card.open_threads) == 1
    assert card.conversation_count == 1


def test_write_managed_roundtrip_readable(cfg):
    path = cfg.vault.insights_path / "People" / "Angela.md"
    write_managed(
        cfg,
        path,
        "Angela leads pricing.\n\n## Open threads\n- Follow up on deck. ([[note]])\n",
        title="Angela",
    )
    body = synth_reader.read_managed_body(path)
    assert "Angela leads pricing" in body
    assert SYNTH_BEGIN not in body
