"""Push-based synthesis: digests, commitments, dossiers, study rollups, prep.

The thesis (from the CEO plan): pull-based personal memory goes unused —
note_categories sat at 0 rows after three attempts at organizing. So instead
of waiting to be asked, synthesis writes into the vault namespaces the user
already lives in:

  Digests/YYYY-MM-DD.md      what happened, with citations
  Digests/Commitments.md     every open "- [ ]" across all notes (mechanical)
  People/<Name>.md           dossiers for people seen >= 3 times
  Studies/<Name>.md          cross-source research rollups
  Prep/YYYY-MM-DD <mtg>.md   tomorrow's meetings: what you owe whom

Rigor rules (non-negotiable, enforced in code — not prompts):
  * Cadence guard: runs at most once per calendar day (meta key), never per
    20-minute sync cycle.
  * Citation gate: every LLM claim must carry a VERBATIM span that string-
    matches the cited source's text; claims that fail are dropped and counted.
  * Managed regions: only the block between synth markers is rewritten, so
    hand annotations survive (writer.write_managed).
  * Namespace isolation: writes are refused outside Digests/People/Studies/Prep.
  * Idempotent: re-running a day rewrites the same files, never duplicates.
  * Change detection: dossiers/studies only spend API calls when their input
    conversations changed (content-hash in meta).
"""
from __future__ import annotations

import hashlib
import json
import sys
from collections import Counter
from dataclasses import dataclass, field
from datetime import date, timedelta
from pathlib import Path
from typing import Iterable, Optional

from ..config import Config, StudyConfig, load_config
from ..db import all_transcripts, get_conn, get_meta, set_meta
from ..models import NoteRecord
from ..obsidian import writer
from .llm import LLM, LLMError

LAST_RUN_KEY = "synthesis_last_run"

CLAIM_SCHEMA = {
    "type": "object",
    "properties": {
        "text": {"type": "string", "description": "The claim, one sentence."},
        "source_id": {"type": "string", "description": "id of the conversation this comes from"},
        "quote": {
            "type": "string",
            "description": "VERBATIM span copied character-for-character from the cited conversation's material",
        },
    },
    "required": ["text", "source_id", "quote"],
}

CITE_RULES = """Citation rules (mechanically enforced — violations are discarded):
- Every claim carries source_id (the conversation's id) and quote.
- quote must be a short span copied VERBATIM from that conversation's material
  exactly as shown to you. Do not paraphrase, trim words mid-phrase, or fix
  grammar inside quote. A claim whose quote does not string-match its source
  is dropped by a validation gate before anything is written."""


# ---------- citation gate (R3: verbatim span, not a syntactic wikilink) ----------

def _norm(s: str) -> str:
    return " ".join(s.casefold().split())


def _haystack(rec: NoteRecord) -> str:
    return _norm(
        "\n".join(
            [rec.title, rec.summary, *rec.action_items, rec.transcript_text]
        )
    )


def verify_claims(
    claims: Iterable[dict], by_id: dict[str, NoteRecord]
) -> tuple[list[dict], int]:
    """Keep only claims whose quote appears verbatim (whitespace/case
    normalized) in the cited conversation. Returns (kept, dropped_count)."""
    kept: list[dict] = []
    dropped = 0
    for c in claims:
        text = str(c.get("text", "")).strip()
        sid = str(c.get("source_id", "")).strip()
        quote = _norm(str(c.get("quote", "")))
        rec = by_id.get(sid)
        if not text or rec is None or not quote or quote not in _haystack(rec):
            dropped += 1
            continue
        kept.append({"text": text, "source_id": sid, "rec": rec})
    return kept, dropped


def _stem(rec: NoteRecord) -> str:
    return Path(rec.note_path).stem if rec.note_path else rec.title


def _claim_line(c: dict) -> str:
    return f"- {c['text']} ([[{_stem(c['rec'])}]])"


def _sanitize(name: str) -> str:
    return name.replace("/", "-").replace("\\", "-").replace(":", "-").strip() or "Untitled"


def _footer(dropped: int) -> str:
    note = f" · {dropped} claim(s) dropped by the citation gate" if dropped else ""
    return f"\n---\n_Generated by transcript-analyzer synthesis{note}._"


# ---------- person identity (R1 + R2: email-keyed, thresholded) ----------

@dataclass
class Person:
    key: str  # lowercased email, or normalized name when no email exists
    email: str = ""
    names: Counter = field(default_factory=Counter)
    records: dict[str, NoteRecord] = field(default_factory=dict)

    @property
    def display_name(self) -> str:
        for name, _n in self.names.most_common():
            if name.strip():
                return name.strip()
        return self.email.split("@")[0] if self.email else self.key


def build_people(records: list[NoteRecord]) -> dict[str, Person]:
    """Identity resolution keyed on email (the stable key granola provides);
    display names become an alias set. People without an email key on their
    normalized name."""
    people: dict[str, Person] = {}
    name_to_email_key: dict[str, str] = {}

    def get(key: str, email: str = "") -> Person:
        p = people.get(key)
        if p is None:
            p = people[key] = Person(key=key, email=email)
        if email and not p.email:
            p.email = email
        return p

    for rec in records:
        for a in rec.attendees:
            key = a.key
            if not key:
                continue
            p = get(key, a.email.strip().lower())
            if a.name.strip():
                p.names[a.name.strip()] += 1
                if a.email.strip():
                    name_to_email_key[_norm(a.name)] = key
            p.records[rec.transcript_id] = rec

    # Fold LLM-extracted display names into email-keyed identities when the
    # name is known; otherwise key on the normalized name.
    for rec in records:
        for name in rec.people:
            norm = _norm(name.replace("_", " "))
            if not norm:
                continue
            key = name_to_email_key.get(norm, norm)
            p = get(key)
            p.names[name.strip()] += 1
            p.records[rec.transcript_id] = rec

    return people


def _self_keys(cfg: Config, people: dict[str, Person], total_records: int) -> set[str]:
    """The vault owner never gets a dossier. Uses config when provided;
    otherwise anyone present in >=60% of conversations is assumed to be
    the owner (they are in nearly every recording they make)."""
    keys: set[str] = set()
    self_names = {_norm(n) for n in cfg.synthesis.self_names}
    self_emails = {e.lower() for e in cfg.synthesis.self_emails}
    for key, p in people.items():
        if p.email and p.email in self_emails:
            keys.add(key)
            continue
        if any(_norm(n) in self_names for n in p.names):
            keys.add(key)
    if not self_names and not self_emails and total_records >= 10:
        for key, p in people.items():
            if len(p.records) >= 0.6 * total_records:
                keys.add(key)
    return keys


# ---------- shared corpus rendering ----------

def _entry(rec: NoteRecord, *, with_open_items: bool = False) -> str:
    people = ", ".join(rec.people) or "(unknown)"
    lines = [
        f"id={rec.transcript_id} | {rec.date} | {rec.title} | people: {people}",
        f"  summary: {' '.join(rec.summary.split()) or '(none)'}",
    ]
    if with_open_items and rec.open_action_items:
        for item in rec.open_action_items:
            lines.append(f"  open action item: {item}")
    return "\n".join(lines)


def _hash_records(records: Iterable[NoteRecord]) -> str:
    h = hashlib.sha256()
    for rec in sorted(records, key=lambda r: r.transcript_id):
        h.update(rec.transcript_id.encode())
        h.update(rec.summary.encode())
        h.update(json.dumps(rec.open_action_items).encode())
    return h.hexdigest()[:16]


# ---------- steps ----------

def commitments(cfg: Config, records: list[NoteRecord]) -> dict:
    """#1 Commitment tracker — pure extraction, zero LLM, zero hallucination.
    State lives in the transcript notes themselves: tick the box in Obsidian
    and the commitment disappears here on the next run."""
    with_open = [r for r in records if r.open_action_items]
    lines = [
        "_Every unchecked action item across all conversations, newest first._",
        "_To close one, tick its checkbox in the linked conversation note._",
        "",
    ]
    total = 0
    for rec in with_open:
        lines.append(f"### [[{_stem(rec)}]] · {rec.date}")
        for item in rec.open_action_items:
            lines.append(f"- [ ] {item}")
            total += 1
        lines.append("")
    if total == 0:
        lines.append("_No open commitments. Clean slate._")
    lines.append(_footer(0))
    path = cfg.vault.insights_path / "Digests" / "Commitments.md"
    writer.write_managed(cfg, path, "\n".join(lines), title="Open Commitments")
    return {"open_items": total, "notes": len(with_open)}


DIGEST_SCHEMA = {
    "type": "object",
    "properties": {
        "headline": {"type": "string", "description": "One sentence: the single most important thing this period."},
        "sections": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "title": {"type": "string"},
                    "claims": {"type": "array", "items": CLAIM_SCHEMA},
                },
                "required": ["title", "claims"],
            },
        },
    },
    "required": ["headline", "sections"],
}

DIGEST_SYSTEM = f"""You are the synthesis engine of a personal conversation-memory
system. You read the user's recent conversations (every one of them, below) and
write the daily digest they will actually read: cross-cutting patterns,
decisions made, things left hanging. Prioritize what changes what the user
should do next. 2-4 sections, 2-5 claims each.

{CITE_RULES}"""


def digest(cfg: Config, llm: LLM, records: list[NoteRecord], today: date) -> dict:
    window_start = (today - timedelta(days=cfg.synthesis.digest_days)).isoformat()
    recent = [r for r in records if r.date >= window_start]
    if not recent:
        return {"skipped": "no conversations in window"}

    by_id = {r.transcript_id: r for r in records}
    corpus = "\n\n".join(_entry(r, with_open_items=True) for r in recent)
    user = (
        f"Today is {today.isoformat()}. Conversations from the last "
        f"{cfg.synthesis.digest_days} days:\n\n{corpus}\n\n"
        "Write the digest."
    )
    data = llm.chat_json(DIGEST_SYSTEM, user, schema=DIGEST_SCHEMA)

    dropped_total = 0
    lines = [f"**{data.get('headline', '').strip()}**", ""]
    for section in data.get("sections", []):
        kept, dropped = verify_claims(section.get("claims", []), by_id)
        dropped_total += dropped
        if not kept:
            continue
        lines.append(f"## {str(section.get('title', 'Notes')).strip()}")
        lines.extend(_claim_line(c) for c in kept)
        lines.append("")
    lines.append("See [[Commitments]] for everything currently open.")
    lines.append(_footer(dropped_total))

    path = cfg.vault.insights_path / "Digests" / f"{today.isoformat()}.md"
    writer.write_managed(
        cfg, path, "\n".join(lines), title=f"Digest · {today.isoformat()}"
    )
    return {"conversations": len(recent), "dropped_claims": dropped_total}


DOSSIER_SCHEMA = {
    "type": "object",
    "properties": {
        "who": {"type": "string", "description": "1-2 sentences: who this person is to the user."},
        "cares_about": {"type": "array", "items": CLAIM_SCHEMA},
        "open_threads": {"type": "array", "items": CLAIM_SCHEMA},
    },
    "required": ["who", "cares_about", "open_threads"],
}

DOSSIER_SYSTEM = f"""You maintain a dossier on one person the user talks with
repeatedly. From the conversations below, extract what this person cares
about and every thread still open between them and the user. This is meeting
preparation material: concrete beats general.

{CITE_RULES}"""


def dossiers(cfg: Config, llm: LLM, records: list[NoteRecord], *, force: bool = False) -> dict:
    people = build_people(records)
    self_keys = _self_keys(cfg, people, len(records))
    threshold = cfg.synthesis.dossier_min_conversations
    qualified = [
        p for key, p in people.items()
        if key not in self_keys and len(p.records) >= threshold
    ]

    written, unchanged = 0, 0
    for p in sorted(qualified, key=lambda p: -len(p.records)):
        recs = sorted(p.records.values(), key=lambda r: r.date, reverse=True)
        digest_hash = _hash_records(recs)
        meta_key = f"dossier_hash:{p.key}"
        path = cfg.vault.insights_path / "People" / f"{_sanitize(p.display_name)}.md"
        with get_conn(cfg.db_path) as conn:
            prev = get_meta(conn, meta_key)
        if prev == digest_hash and path.exists() and not force:
            unchanged += 1
            continue

        by_id = {r.transcript_id: r for r in recs}
        corpus = "\n\n".join(_entry(r, with_open_items=True) for r in recs)
        aliases = ", ".join(sorted({n for n in p.names if n.strip()})) or p.display_name
        user = (
            f"Person: {p.display_name}"
            + (f" <{p.email}>" if p.email else "")
            + (f" (also appears as: {aliases})" if len(p.names) > 1 else "")
            + f"\n\nAll {len(recs)} conversations with them:\n\n{corpus}"
        )
        data = llm.chat_json(DOSSIER_SYSTEM, user, schema=DOSSIER_SCHEMA)

        cares, d1 = verify_claims(data.get("cares_about", []), by_id)
        threads, d2 = verify_claims(data.get("open_threads", []), by_id)
        dropped = d1 + d2

        lines = [str(data.get("who", "")).strip(), ""]
        if p.email:
            lines.append(f"**Email:** {p.email}  ")
        if len(p.names) > 1:
            lines.append(f"**Also appears as:** {aliases}")
        lines.append("")
        if cares:
            lines.append("## What they care about")
            lines.extend(_claim_line(c) for c in cares)
            lines.append("")
        if threads:
            lines.append("## Open threads")
            lines.extend(_claim_line(c) for c in threads)
            lines.append("")
        lines.append("## Conversations")
        lines.extend(f"- [[{_stem(r)}]] · {r.date}" for r in recs)
        lines.append(_footer(dropped))

        writer.write_managed(cfg, path, "\n".join(lines), title=p.display_name)
        with get_conn(cfg.db_path) as conn:
            set_meta(conn, meta_key, digest_hash)
        written += 1

    return {
        "people_total": len(people),
        "qualified": len(qualified),
        "written": written,
        "unchanged": unchanged,
    }


MEMBERSHIP_SCHEMA = {
    "type": "object",
    "properties": {
        "member_ids": {
            "type": "array",
            "items": {"type": "string"},
            "description": "ids of conversations that belong to this study",
        }
    },
    "required": ["member_ids"],
}

ROLLUP_SCHEMA = {
    "type": "object",
    "properties": {
        "overview": {"type": "string", "description": "2-3 sentences: what this study is and where it stands."},
        "findings": {"type": "array", "items": CLAIM_SCHEMA},
        "open_questions": {"type": "array", "items": {"type": "string"}},
    },
    "required": ["overview", "findings", "open_questions"],
}

ROLLUP_SYSTEM = f"""You synthesize a research study from the user's interview and
observation sessions (all sessions below). Surface recurring patterns across
sessions — a finding seen in three sessions beats a striking one-off. Note
contradictions honestly.

{CITE_RULES}"""


def studies(cfg: Config, llm: LLM, records: list[NoteRecord], *, force: bool = False) -> dict:
    results = {}
    if not cfg.synthesis.studies:
        return {"skipped": "no studies configured"}
    index = "\n\n".join(_entry(r) for r in records)
    by_id = {r.transcript_id: r for r in records}

    for study in cfg.synthesis.studies:
        members = _classify_members(llm, study, index, by_id)
        if not members:
            results[study.name] = {"skipped": "no matching sessions"}
            continue
        digest_hash = _hash_records(members)
        meta_key = f"study_hash:{study.name}"
        path = cfg.vault.insights_path / "Studies" / f"{_sanitize(study.name)}.md"
        with get_conn(cfg.db_path) as conn:
            prev = get_meta(conn, meta_key)
        if prev == digest_hash and path.exists() and not force:
            results[study.name] = {"unchanged": len(members)}
            continue

        member_by_id = {r.transcript_id: r for r in members}
        corpus = "\n\n".join(
            _entry(r) for r in sorted(members, key=lambda r: r.date)
        )
        user = (
            f"Study: {study.name}\nDescription: {study.description}\n\n"
            f"All {len(members)} sessions:\n\n{corpus}"
        )
        data = llm.chat_json(ROLLUP_SYSTEM, user, schema=ROLLUP_SCHEMA)
        findings, dropped = verify_claims(data.get("findings", []), member_by_id)

        lines = [str(data.get("overview", "")).strip(), ""]
        if findings:
            lines.append("## Findings")
            lines.extend(_claim_line(c) for c in findings)
            lines.append("")
        oq = [str(q).strip() for q in data.get("open_questions", []) if str(q).strip()]
        if oq:
            lines.append("## Open questions")
            lines.extend(f"- {q}" for q in oq)
            lines.append("")
        lines.append("## Sessions")
        lines.extend(
            f"- [[{_stem(r)}]] · {r.date} ({r.source})"
            for r in sorted(members, key=lambda r: r.date, reverse=True)
        )
        lines.append(_footer(dropped))

        writer.write_managed(cfg, path, "\n".join(lines), title=study.name)
        with get_conn(cfg.db_path) as conn:
            set_meta(conn, meta_key, digest_hash)
        results[study.name] = {"sessions": len(members), "dropped_claims": dropped}
    return results


def _classify_members(
    llm: LLM, study: StudyConfig, index: str, by_id: dict[str, NoteRecord]
) -> list[NoteRecord]:
    system = (
        "You classify which of the user's conversations belong to a research "
        "study. Include a conversation only when its content clearly matches "
        "the study description. Return the ids only."
    )
    user = (
        f"Study: {study.name}\nDescription: {study.description}\n\n"
        f"All conversations:\n\n{index}"
    )
    data = llm.chat_json(system, user, schema=MEMBERSHIP_SCHEMA)
    ids = {str(i).strip() for i in data.get("member_ids", [])}
    return [by_id[i] for i in ids if i in by_id]


PREP_SCHEMA = {
    "type": "object",
    "properties": {
        "points": {"type": "array", "items": CLAIM_SCHEMA},
    },
    "required": ["points"],
}

PREP_SYSTEM = f"""You write a short meeting-prep note. From the history below,
surface what the user owes these people, what the people cared about last
time, and anything left unresolved. 3-7 points, most actionable first.

{CITE_RULES}"""


def prep(cfg: Config, llm: LLM, records: list[NoteRecord], today: date) -> dict:
    """#5 Meeting prep — daily batch (R10): each run preps *tomorrow's*
    calendar, joined to conversation history on attendee email."""
    if not cfg.calendar.enabled:
        return {"skipped": "no [calendar] ics_url configured"}
    from ..calendar_feed import events_for_day

    tomorrow = today + timedelta(days=1)
    try:
        events = events_for_day(cfg, tomorrow)
    except Exception as e:  # noqa: BLE001 - a broken feed must not kill synthesis
        return {"error": f"calendar fetch failed: {e}"}
    if not events:
        return {"skipped": "no events tomorrow"}

    people = build_people(records)
    self_keys = _self_keys(cfg, people, len(records))
    by_email = {p.email: p for p in people.values() if p.email}
    by_name = {_norm(n): p for p in people.values() for n in p.names}

    written = 0
    for ev in events:
        matched: dict[str, "Person"] = {}
        for email in ev.attendee_emails:
            p = by_email.get(email.lower())
            if p and p.key not in self_keys:
                matched[p.key] = p
        for name in ev.attendee_names:
            p = by_name.get(_norm(name))
            if p and p.key not in self_keys:
                matched.setdefault(p.key, p)
        if not matched:
            continue  # nobody we have history with — nothing to prep

        recs: dict[str, NoteRecord] = {}
        for p in matched.values():
            recs.update(p.records)
        ordered = sorted(recs.values(), key=lambda r: r.date, reverse=True)[:12]
        by_id = {r.transcript_id: r for r in ordered}
        names = ", ".join(sorted(p.display_name for p in matched.values()))
        corpus = "\n\n".join(_entry(r, with_open_items=True) for r in ordered)
        user = (
            f"Meeting tomorrow ({tomorrow.isoformat()}): {ev.title}\n"
            f"With: {names}\n\nConversation history with them:\n\n{corpus}"
        )
        try:
            data = llm.chat_json(PREP_SYSTEM, user, schema=PREP_SCHEMA)
        except LLMError as e:
            print(f"[synthesize] prep failed for {ev.title!r}: {e}", file=sys.stderr)
            continue
        points, dropped = verify_claims(data.get("points", []), by_id)

        lines = [f"**{ev.title}** · {tomorrow.isoformat()} · with {names}", ""]
        if points:
            lines.extend(_claim_line(c) for c in points)
        else:
            lines.append("_No verifiable prep points extracted._")
        open_items = [
            (item, r) for r in ordered for item in r.open_action_items
        ]
        if open_items:
            lines.append("")
            lines.append("## Still open with them")
            lines.extend(f"- [ ] {item} ([[{_stem(r)}]])" for item, r in open_items)
        lines.append(_footer(dropped))

        fname = f"{tomorrow.isoformat()} {_sanitize(ev.title)[:60]}.md"
        path = cfg.vault.insights_path / "Prep" / fname
        writer.write_managed(cfg, path, "\n".join(lines), title=f"Prep · {ev.title}")
        written += 1

    return {"events": len(events), "prepped": written}


# ---------- orchestration ----------

ALL_STEPS = ("commitments", "digest", "dossiers", "studies", "prep")


def run(
    cfg: Optional[Config] = None,
    llm: Optional[LLM] = None,
    *,
    only: Optional[set[str]] = None,
    force: bool = False,
    verbose: bool = True,
) -> dict:
    cfg = cfg or load_config()
    llm = llm or LLM(cfg)
    today = date.today()
    with get_conn(cfg.db_path) as conn:
        records = all_transcripts(conn)
    if not records:
        return {"skipped": "index is empty"}

    steps = set(only) if only else set(ALL_STEPS)
    summary: dict = {}
    if "commitments" in steps:
        summary["commitments"] = commitments(cfg, records)
    if "digest" in steps:
        summary["digest"] = digest(cfg, llm, records, today)
    if "dossiers" in steps:
        summary["dossiers"] = dossiers(cfg, llm, records, force=force)
    if "studies" in steps:
        summary["studies"] = studies(cfg, llm, records, force=force)
    if "prep" in steps:
        summary["prep"] = prep(cfg, llm, records, today)
    if verbose:
        print(f"[synthesize] {json.dumps(summary, default=str)}")
    return summary


def maybe_run(
    cfg: Optional[Config] = None,
    llm: Optional[LLM] = None,
    *,
    verbose: bool = True,
) -> Optional[dict]:
    """Cadence guard: at most one synthesis pass per calendar day. Budget and
    kill-switch errors propagate (nothing has been half-written by then that
    a next run wouldn't redo); the day marker is only set after a full pass,
    so a failed pass retries on the next sync cycle."""
    cfg = cfg or load_config()
    today = date.today().isoformat()
    with get_conn(cfg.db_path) as conn:
        if get_meta(conn, LAST_RUN_KEY) == today:
            return None
    summary = run(cfg, llm, verbose=verbose)
    with get_conn(cfg.db_path) as conn:
        set_meta(conn, LAST_RUN_KEY, today)
    return summary
