"""Read synthesis vault notes into structures the dashboard can render.

The vault remains the source of truth (Digests / People / Studies / Prep).
This module only parses managed regions — it never re-runs the LLM.
"""
from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Optional

from ..config import Config
from ..db import all_transcripts, get_conn, get_meta
from ..models import NoteRecord
from ..obsidian.writer import SYNTH_BEGIN, SYNTH_END
from ..pipeline.synthesize import LAST_RUN_KEY

WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
HEADING_RE = re.compile(r"^##\s+(.+)$")
BULLET_RE = re.compile(r"^-\s+(?:\[[ xX]\]\s+)?(.+)$")


@dataclass
class Claim:
    text: str
    wiki_stem: str = ""
    transcript_id: str = ""
    title: str = ""


@dataclass
class DigestSection:
    title: str
    claims: list[Claim] = field(default_factory=list)


@dataclass
class DigestView:
    date: str
    path: Path
    title: str
    headline: str = ""
    sections: list[DigestSection] = field(default_factory=list)
    exists: bool = False


@dataclass
class CommitmentGroup:
    wiki_stem: str
    date: str
    items: list[str] = field(default_factory=list)
    transcript_id: str = ""
    title: str = ""


@dataclass
class PersonCard:
    name: str
    path: Path
    who: str = ""
    cares_about: list[Claim] = field(default_factory=list)
    open_threads: list[Claim] = field(default_factory=list)
    conversations: list[Claim] = field(default_factory=list)
    conversation_count: int = 0


@dataclass
class StudyCard:
    name: str
    path: Path
    overview: str = ""
    findings: list[Claim] = field(default_factory=list)
    open_questions: list[str] = field(default_factory=list)
    sessions: list[Claim] = field(default_factory=list)


@dataclass
class CategoryInsight:
    name: str
    path: Path
    overview: str = ""
    themes: list[Claim] = field(default_factory=list)
    open_threads: list[Claim] = field(default_factory=list)
    open_commitments: list[Claim] = field(default_factory=list)
    conversations: list[Claim] = field(default_factory=list)
    exists: bool = False


@dataclass
class PrepCard:
    name: str
    path: Path
    date: str = ""
    headline: str = ""
    points: list[Claim] = field(default_factory=list)
    still_open: list[Claim] = field(default_factory=list)


def insights_root(cfg: Config) -> Path:
    return cfg.vault.insights_path


def stem_index(records: list[NoteRecord]) -> dict[str, NoteRecord]:
    out: dict[str, NoteRecord] = {}
    for rec in records:
        if not rec.note_path:
            continue
        out[Path(rec.note_path).stem] = rec
    return out


def resolve_claim(text: str, by_stem: dict[str, NoteRecord]) -> Claim:
    """Strip trailing wikilink from a bullet and attach transcript metadata."""
    stem = ""
    m = WIKILINK_RE.search(text)
    if m:
        stem = m.group(1).strip()
        text = WIKILINK_RE.sub("", text).rstrip(" ·").strip()
    rec = by_stem.get(stem)
    return Claim(
        text=text,
        wiki_stem=stem,
        transcript_id=rec.transcript_id if rec else "",
        title=rec.title if rec else stem,
    )


def read_managed_body(path: Path) -> str:
    if not path.exists():
        return ""
    text = path.read_text(encoding="utf-8")
    begin = text.find(SYNTH_BEGIN)
    end = text.find(SYNTH_END)
    if begin != -1 and end != -1 and end > begin:
        return text[begin + len(SYNTH_BEGIN) : end].strip()
    # Fallback: strip frontmatter and use the rest.
    if text.startswith("---"):
        parts = text.split("---", 2)
        if len(parts) >= 3:
            return parts[2].strip()
    return text.strip()


def _strip_footer(body: str) -> str:
    lines = body.splitlines()
    while lines and (
        lines[-1].startswith("_Generated by")
        or lines[-1].strip() == "---"
        or not lines[-1].strip()
    ):
        lines.pop()
    return "\n".join(lines).strip()


def parse_digest(body: str, by_stem: dict[str, NoteRecord]) -> tuple[str, list[DigestSection]]:
    body = _strip_footer(body)
    lines = body.splitlines()
    headline = ""
    sections: list[DigestSection] = []
    current: Optional[DigestSection] = None
    i = 0
    while i < len(lines):
        ln = lines[i].rstrip()
        if not headline and ln.startswith("**") and ln.endswith("**") and len(ln) > 4:
            headline = ln.strip("*").strip()
            i += 1
            continue
        hm = HEADING_RE.match(ln)
        if hm:
            title = hm.group(1).strip()
            if title.lower().startswith("see "):
                i += 1
                continue
            current = DigestSection(title=title)
            sections.append(current)
            i += 1
            continue
        bm = BULLET_RE.match(ln)
        if bm and current is not None:
            current.claims.append(resolve_claim(bm.group(1), by_stem))
        elif ln.startswith("See [["):
            pass
        i += 1
    return headline, sections


def latest_digest(cfg: Config, by_stem: dict[str, NoteRecord], *, today: Optional[date] = None) -> DigestView:
    today = today or date.today()
    digests_dir = insights_root(cfg) / "Digests"
    # Prefer today's file; otherwise the newest dated digest.
    today_path = digests_dir / f"{today.isoformat()}.md"
    if today_path.exists():
        path = today_path
        day = today.isoformat()
    else:
        dated = sorted(
            (p for p in digests_dir.glob("????-??-??.md") if p.name != "Commitments.md"),
            reverse=True,
        )
        if not dated:
            return DigestView(date=today.isoformat(), path=today_path, title="Digest", exists=False)
        path = dated[0]
        day = path.stem
    body = read_managed_body(path)
    headline, sections = parse_digest(body, by_stem)
    return DigestView(
        date=day,
        path=path,
        title=f"Digest · {day}",
        headline=headline,
        sections=sections,
        exists=True,
    )


def list_digest_dates(cfg: Config) -> list[str]:
    digests_dir = insights_root(cfg) / "Digests"
    if not digests_dir.exists():
        return []
    return sorted(
        (p.stem for p in digests_dir.glob("????-??-??.md")),
        reverse=True,
    )


def load_digest(cfg: Config, day: str, by_stem: dict[str, NoteRecord]) -> DigestView:
    path = insights_root(cfg) / "Digests" / f"{day}.md"
    if not path.exists():
        return DigestView(date=day, path=path, title=f"Digest · {day}", exists=False)
    headline, sections = parse_digest(read_managed_body(path), by_stem)
    return DigestView(
        date=day,
        path=path,
        title=f"Digest · {day}",
        headline=headline,
        sections=sections,
        exists=True,
    )


def commitments_from_records(records: list[NoteRecord]) -> list[CommitmentGroup]:
    """Live commitments from the index (same data Commitments.md is built from)."""
    groups: list[CommitmentGroup] = []
    for rec in records:
        if not rec.open_action_items:
            continue
        groups.append(
            CommitmentGroup(
                wiki_stem=Path(rec.note_path).stem if rec.note_path else rec.title,
                date=rec.date,
                items=list(rec.open_action_items),
                transcript_id=rec.transcript_id,
                title=rec.title,
            )
        )
    return groups


def parse_person(body: str, by_stem: dict[str, NoteRecord]) -> PersonCard:
    body = _strip_footer(body)
    who_lines: list[str] = []
    cares: list[Claim] = []
    threads: list[Claim] = []
    convos: list[Claim] = []
    section = ""
    for ln in body.splitlines():
        hm = HEADING_RE.match(ln)
        if hm:
            section = hm.group(1).strip().lower()
            continue
        if ln.startswith("**Email:**") or ln.startswith("**Also appears as:**"):
            continue
        bm = BULLET_RE.match(ln)
        if bm:
            claim = resolve_claim(bm.group(1), by_stem)
            if section.startswith("what they care"):
                cares.append(claim)
            elif section.startswith("open thread"):
                threads.append(claim)
            elif section.startswith("conversation"):
                convos.append(claim)
            continue
        if not section and ln.strip() and not ln.startswith("_"):
            who_lines.append(ln.strip())
    return PersonCard(
        name="",
        path=Path(),
        who=" ".join(who_lines).strip(),
        cares_about=cares,
        open_threads=threads,
        conversations=convos,
        conversation_count=len(convos),
    )


def list_people(cfg: Config, by_stem: dict[str, NoteRecord]) -> list[PersonCard]:
    people_dir = insights_root(cfg) / "People"
    if not people_dir.exists():
        return []
    cards: list[PersonCard] = []
    for path in sorted(people_dir.glob("*.md"), key=lambda p: p.stem.lower()):
        card = parse_person(read_managed_body(path), by_stem)
        card.name = path.stem
        card.path = path
        cards.append(card)
    return sorted(cards, key=lambda c: (-c.conversation_count, c.name.lower()))


def load_person(cfg: Config, name: str, by_stem: dict[str, NoteRecord]) -> Optional[PersonCard]:
    path = insights_root(cfg) / "People" / f"{name}.md"
    if not path.exists():
        # Case-insensitive fallback
        people_dir = path.parent
        if people_dir.exists():
            for p in people_dir.glob("*.md"):
                if p.stem.lower() == name.lower():
                    path = p
                    break
            else:
                return None
        else:
            return None
    card = parse_person(read_managed_body(path), by_stem)
    card.name = path.stem
    card.path = path
    return card


def parse_study(body: str, by_stem: dict[str, NoteRecord]) -> StudyCard:
    body = _strip_footer(body)
    overview_lines: list[str] = []
    findings: list[Claim] = []
    questions: list[str] = []
    sessions: list[Claim] = []
    section = ""
    for ln in body.splitlines():
        hm = HEADING_RE.match(ln)
        if hm:
            section = hm.group(1).strip().lower()
            continue
        bm = BULLET_RE.match(ln)
        if bm:
            if section.startswith("finding"):
                findings.append(resolve_claim(bm.group(1), by_stem))
            elif section.startswith("open question"):
                questions.append(bm.group(1).strip())
            elif section.startswith("session"):
                sessions.append(resolve_claim(bm.group(1), by_stem))
            continue
        if not section and ln.strip() and not ln.startswith("_"):
            overview_lines.append(ln.strip())
    return StudyCard(
        name="",
        path=Path(),
        overview=" ".join(overview_lines).strip(),
        findings=findings,
        open_questions=questions,
        sessions=sessions,
    )


def list_studies(cfg: Config, by_stem: dict[str, NoteRecord]) -> list[StudyCard]:
    studies_dir = insights_root(cfg) / "Studies"
    if not studies_dir.exists():
        return []
    out: list[StudyCard] = []
    for path in sorted(studies_dir.glob("*.md"), key=lambda p: p.stem.lower()):
        card = parse_study(read_managed_body(path), by_stem)
        card.name = path.stem
        card.path = path
        out.append(card)
    return out


def load_study(cfg: Config, name: str, by_stem: dict[str, NoteRecord]) -> Optional[StudyCard]:
    path = insights_root(cfg) / "Studies" / f"{name}.md"
    if not path.exists():
        return None
    card = parse_study(read_managed_body(path), by_stem)
    card.name = path.stem
    card.path = path
    return card


def parse_category(body: str, by_stem: dict[str, NoteRecord]) -> CategoryInsight:
    body = _strip_footer(body)
    overview_lines: list[str] = []
    themes: list[Claim] = []
    threads: list[Claim] = []
    commitments: list[Claim] = []
    convos: list[Claim] = []
    section = ""
    for ln in body.splitlines():
        hm = HEADING_RE.match(ln)
        if hm:
            section = hm.group(1).strip().lower()
            continue
        if not section and ln.startswith("**") and "·" in ln:
            continue  # skip "**Fundraising** · N conversation(s)" title line
        bm = BULLET_RE.match(ln)
        if bm:
            claim = resolve_claim(bm.group(1), by_stem)
            if section.startswith("theme"):
                themes.append(claim)
            elif section.startswith("open thread"):
                threads.append(claim)
            elif section.startswith("open commitment"):
                commitments.append(claim)
            elif section.startswith("conversation"):
                convos.append(claim)
            continue
        if not section and ln.strip() and not ln.startswith("_"):
            overview_lines.append(ln.strip())
    return CategoryInsight(
        name="",
        path=Path(),
        overview=" ".join(overview_lines).strip(),
        themes=themes,
        open_threads=threads,
        open_commitments=commitments,
        conversations=convos,
        exists=True,
    )


def load_category_insight(
    cfg: Config, name: str, by_stem: dict[str, NoteRecord]
) -> CategoryInsight:
    from ..pipeline.organize import category_note_path

    path = category_note_path(cfg, name)
    if not path.exists():
        # Case-insensitive fallback
        cats_dir = path.parent
        if cats_dir.exists():
            for p in cats_dir.glob("*.md"):
                if p.stem.lower() == name.lower() and p.stem != "Categories":
                    path = p
                    break
            else:
                return CategoryInsight(name=name, path=path, exists=False)
        else:
            return CategoryInsight(name=name, path=path, exists=False)
    card = parse_category(read_managed_body(path), by_stem)
    card.name = path.stem
    card.path = path
    card.exists = True
    return card


def parse_prep(body: str, by_stem: dict[str, NoteRecord]) -> PrepCard:
    body = _strip_footer(body)
    lines = body.splitlines()
    headline = ""
    points: list[Claim] = []
    still_open: list[Claim] = []
    section = ""
    for ln in lines:
        hm = HEADING_RE.match(ln)
        if hm:
            section = hm.group(1).strip().lower()
            continue
        if not headline and ln.startswith("**"):
            headline = ln.strip("*").strip()
            # Often "**Title** · date · with names"
            continue
        bm = BULLET_RE.match(ln)
        if bm:
            claim = resolve_claim(bm.group(1), by_stem)
            if section.startswith("still open"):
                still_open.append(claim)
            else:
                points.append(claim)
    return PrepCard(
        name="",
        path=Path(),
        headline=headline,
        points=points,
        still_open=still_open,
    )


def list_prep(cfg: Config, by_stem: dict[str, NoteRecord]) -> list[PrepCard]:
    prep_dir = insights_root(cfg) / "Prep"
    if not prep_dir.exists():
        return []
    out: list[PrepCard] = []
    for path in sorted(prep_dir.glob("*.md"), reverse=True):
        card = parse_prep(read_managed_body(path), by_stem)
        card.name = path.stem
        card.path = path
        # Filename: YYYY-MM-DD Title
        parts = path.stem.split(" ", 1)
        if parts and re.match(r"\d{4}-\d{2}-\d{2}", parts[0]):
            card.date = parts[0]
        out.append(card)
    return out


def synthesis_status(cfg: Config) -> dict:
    with get_conn(cfg.db_path) as conn:
        last = get_meta(conn, LAST_RUN_KEY)
    today = date.today().isoformat()
    return {
        "last_run": last,
        "ran_today": last == today,
        "enabled": cfg.synthesis.enabled,
        "today": today,
    }


def load_briefing(cfg: Config) -> dict:
    """Everything the home page needs in one pass."""
    with get_conn(cfg.db_path) as conn:
        records = all_transcripts(conn)
    by_stem = stem_index(records)
    digest = latest_digest(cfg, by_stem)
    commitments = commitments_from_records(records)
    people = list_people(cfg, by_stem)
    studies = list_studies(cfg, by_stem)
    prep = list_prep(cfg, by_stem)
    open_count = sum(len(g.items) for g in commitments)
    return {
        "records": records,
        "by_stem": by_stem,
        "digest": digest,
        "commitments": commitments,
        "open_count": open_count,
        "people": people,
        "studies": studies,
        "prep": prep,
        "status": synthesis_status(cfg),
        "total": len(records),
    }
